// Code generated by MockGen. DO NOT EDIT.
// Source: Faceit/src/internal/ports (interfaces: PublisherService)

// Package mocks is a generated GoMock package.
package mocks

import (
	model "Faceit/src/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPublisherService is a mock of PublisherService interface.
type MockPublisherService struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherServiceMockRecorder
}

// MockPublisherServiceMockRecorder is the mock recorder for MockPublisherService.
type MockPublisherServiceMockRecorder struct {
	mock *MockPublisherService
}

// NewMockPublisherService creates a new mock instance.
func NewMockPublisherService(ctrl *gomock.Controller) *MockPublisherService {
	mock := &MockPublisherService{ctrl: ctrl}
	mock.recorder = &MockPublisherServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisherService) EXPECT() *MockPublisherServiceMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MockPublisherService) Connect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect")
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockPublisherServiceMockRecorder) Connect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockPublisherService)(nil).Connect))
}

// Publish mocks base method.
func (m *MockPublisherService) Publish(arg0 model.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockPublisherServiceMockRecorder) Publish(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockPublisherService)(nil).Publish), arg0)
}

// Reconnect mocks base method.
func (m *MockPublisherService) Reconnect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconnect")
	ret0, _ := ret[0].(error)
	return ret0
}

// Reconnect indicates an expected call of Reconnect.
func (mr *MockPublisherServiceMockRecorder) Reconnect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconnect", reflect.TypeOf((*MockPublisherService)(nil).Reconnect))
}
